import './globals.css'
import Header from '@/components/header'
// import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import { SidebarProvider } from '../context/SidebarContext';
import Breadcrumbs from '@/components/BreadcrumbV2';
// const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Cronode',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex flex-1 flex-row overflow-y-hidden">
            <Sidebar/>
            <main className="h-screen flex-1 overflow-y-auto">
              <Header/>
              <div className="m-4"><Breadcrumbs/></div>
              {children}
            </main>
          </div>
        </SidebarProvider>
        
      </body>

    </html>
  )
}